services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hypersave
    environment:
      - .env
    depends_on:
      - postgres


  postgres:
    image: postgres:17
    container_name: postgres_hypersave
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: